# Generated by Django 5.0.2 on 2024-08-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
