# Generated by Django 5.0.2 on 2024-09-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_massage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
